all_hosts = Linux FreeBSD

ifeq ($(OS),)
SYS := $(shell gcc49 -dumpmachine)
ifeq ($(SYS),x86_64-linux-gnu)
OS := Linux
else ifeq ($(SYS), x86_64-portbld-freebsd10.0)
OS := FreeBSD
else
$(error Unsupported platform: $(SYS))
endif
else
ifeq ($(findstring $(OS),$(all_hosts)),)
$(error Unsupported platform: $(OS))
endif
endif
